### ISSUE TITLE
Dead await warning causes fatal exception when trace undefined

### ISSUE THREAD

**Issue by doublerebel** [maxtaco/iced-runtime#1]
Hello,

I managed to create myself a dead await, and discovered the error message was incorrect.  I received the error:

``` sh
/project/node-webhooks/node_modules/iced-runtime/lib/runtime.js:54
fn = tr[C.funcname] || "<anonymous>";
^
TypeError: Cannot read property 'funcname' of undefined
at _trace_to_string (/project/node-webhooks/node_modules/iced-runtime/lib/runtime.js:54:12)
at Deferrals.exports.Deferrals.Deferrals._call (/project/node-webhooks/node_modules/iced-runtime/lib/runtime.js:88:49)
at /project/node-webhooks/node_modules/iced-runtime/lib/runtime.js:98:26
at exports.trampoline.trampoline (/project/node-webhooks/node_modules/iced-runtime/lib/runtime.js:64:14)
at Deferrals.exports.Deferrals.Deferrals._fulfill (/project/node-webhooks/node_modules/iced-runtime/lib/runtime.js:96:16)
```

Tracing the error, I see that **iced-runtime** attempted to warn me of a dead await.  However, `__iced_deferrals._fulfill()` is called with no arguments, so no trace is passed through to `_trace_to_string`.

My script is compiled with iced-coffee-script@1.7.1-f and using iced-runtime@1.0.1 , so I'm not sure where the fix belongs.

Thanks again for these very useful libs!

**Comment by maxtaco** [comment]
Interesting, I couldn't reproduce this.  Can you send me a test case that shows this issue? 

Also, I wonder if `C` or `tr` is undefined in that function.  It could be either one, since `C.funcname` evaluates to `funcname` ...

**Comment by doublerebel** [comment]
Based on the timing I must have done something around [this commit to node-webhooks](https://github.com/doublerebel/node-webhooks/commit/8fe66e49ff9b8fe3e9a6bf70c687b1d3a3453d0e), in the loadHooks method.  I haven't reproduced it since, so I'll close this issue.  Thanks!
